#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
# htmlproofer tests—[README](https://github.com/gjtorikian/html-proofer/blob/master/README.md)
bundle exec htmlproofer --disable-external ./_site
